paths:
  /api/products:
    get:
      summary: Obtiene todos los productos disponibles en la aplicación.
      tags:
        - Products
      responses:
        "200":
          description: La operacion fue exitosa se retorna un arreglo con los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "400":
          description: Se envió un dato no esperado
        "500":
          description: Error inesperado en el servidor
  /api/products/{id}:
    get:
      summary: Obtiene el usuario con el id disponible en la app.
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id del usuario que desea solicitar
        schema:
          $type: string
      responses:
        "200":
          description: La operacion fue exitosa se retorna un producto
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "400":
          description: Se envió un dato no esperado
        "500":
          description: Error inesperado en el servidor

components:
  schemas:
    Products:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción o características del producto
        code:
          type: string
          description: Código único del producto
        price:
          type: number
          description: Valor de venta del producto
        status:
          type: boolean
          description: Estado del producto (disponible o no)
        stock:
          type: number
          description: Cantidad de productos disponibles
        owner:
          type: string
          description: Usuario que dio de alta el producto
        category:
          type: string
          description: Categoría del producto (computadoras, telefonos, etc.)
        thumbnails:
          type: array
          items:
            type: string
          default: []